# Generated by Django 3.2.5 on 2021-07-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=255)),
                ('midddle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=250, null=True)),
                ('education', models.CharField(blank=True, choices=[('illiterate', 'Illiterate'), ('primary', 'Primary'), ('matriculation', 'MATRICULATION'), ('senior_secondary', 'Senior Secondary'), ('graduation', 'Graduation'), ('post_graduation', 'Post Graduation')], max_length=250, null=True)),
                ('category', models.CharField(blank=True, choices=[('real_estate', 'Real Estate'), ('animal_breeding', 'Animal Breeding'), ('others', 'Others')], max_length=250, null=True)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('referral_key', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('refer_count', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
