# Generated by Django 3.2.5 on 2021-07-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210725_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreferralbridge',
            old_name='user_id_id',
            new_name='user_id',
        ),
        migrations.AlterModelTable(
            name='appuser',
            table='app_user',
        ),
        migrations.AlterModelTable(
            name='userreferralbridge',
            table='user_referral_bridge',
        ),
    ]
